FROM alpine:3.18.0

ARG group
ARG application
ARG description
ARG version
ARG repository
ARG branch
ARG commit
ARG commit_before
ARG commit_time
ARG commit_timestamp
ARG commit_message
ARG commit_author
ARG commit_author_email
ARG build
ARG ci
ARG github_action
ARG github_action_path
ARG github_action_repository
ARG github_actions
ARG github_actor
ARG github_actor_id
ARG github_api_url
ARG github_base_ref
ARG github_env
ARG github_event_name
ARG github_event_path
ARG github_graphql_url
ARG github_head_ref
ARG github_job
ARG github_path
ARG github_ref
ARG github_ref_name
ARG github_ref_protected
ARG github_ref_type
ARG github_repository
ARG github_repository_id
ARG github_repository_owner
ARG github_repository_owner_id
ARG github_retention_days
ARG github_run_attempt
ARG github_run_id
ARG github_run_number
ARG github_server_url
ARG github_sha
ARG github_step_summary
ARG github_workflow
ARG github_workflow_ref
ARG github_workflow_sha
ARG github_workspace
ARG runner_arch
ARG runner_debug
ARG runner_name
ARG runner_os

LABEL group="$group"
LABEL application="$application"
LABEL description="$description"
LABEL version="$version"
LABEL repository="$repository"
LABEL branch="$branch"
LABEL commit="$commit"
LABEL commit_before="$commit_before"
LABEL commit_time="$commit_time"
LABEL commit_timestamp="$commit_timestamp"
LABEL commit_message="$commit_message"
LABEL commit_author="$commit_author"
LABEL commit_author_email="$commit_author_email"
LABEL build="$build"
LABEL ci="$ci"
LABEL github_action="$github_action"
LABEL github_action_path="$github_action_path"
LABEL github_action_repository="$github_action_repository"
LABEL github_actions="$github_actions"
LABEL github_actor="$github_actor"
LABEL github_actor_id="$github_actor_id"
LABEL github_api_url="$github_api_url"
LABEL github_base_ref="$github_base_ref"
LABEL github_env="$github_env"
LABEL github_event_name="$github_event_name"
LABEL github_event_path="$github_event_path"
LABEL github_graphql_url="$github_graphql_url"
LABEL github_head_ref="$github_head_ref"
LABEL github_job="$github_job"
LABEL github_path="$github_path"
LABEL github_ref="$github_ref"
LABEL github_ref_name="$github_ref_name"
LABEL github_ref_protected="$github_ref_protected"
LABEL github_ref_type="$github_ref_type"
LABEL github_repository="$github_repository"
LABEL github_repository_id="$github_repository_id"
LABEL github_repository_owner="$github_repository_owner"
LABEL github_repository_owner_id="$github_repository_owner_id"
LABEL github_retention_days="$github_retention_days"
LABEL github_run_attempt="$github_run_attempt"
LABEL github_run_id="$github_run_id"
LABEL github_run_number="$github_run_number"
LABEL github_server_url="$github_server_url"
LABEL github_sha="$github_sha"
LABEL github_step_summary="$github_step_summary"
LABEL github_workflow="$github_workflow"
LABEL github_workflow_ref="$github_workflow_ref"
LABEL github_workflow_sha="$github_workflow_sha"
LABEL github_workspace="$github_workspace"
LABEL runner_arch="$runner_arch"
LABEL runner_debug="$runner_debug"
LABEL runner_name="$runner_name"
LABEL runner_os="$runner_os"

ENV GROUP="$group"
ENV APPLICATION="$application"
ENV DESCRIPTION="$description"
ENV VERSION="$version"
ENV REPOSITORY="$repository"
ENV BRANCH="$branch"
ENV COMMIT="$commit"
ENV COMMIT_BEFORE="$commit_before"
ENV COMMIT_TIME="$commit_time"
ENV COMMIT_TIMESTAMP="$commit_timestamp"
ENV COMMIT_MESSAGE="$commit_message"
ENV COMMIT_AUTHOR="$commit_author"
ENV COMMIT_AUTHOR_EMAIL="$commit_author_email"
ENV BUILD="$build"
ENV CI="$ci"
ENV GITHUB_ACTION="$github_action"
ENV GITHUB_ACTION_PATH="$github_action_path"
ENV GITHUB_ACTION_REPOSITORY="$github_action_repository"
ENV GITHUB_ACTIONS="$github_actions"
ENV GITHUB_ACTOR="$github_actor"
ENV GITHUB_ACTOR_ID="$github_actor_id"
ENV GITHUB_API_URL="$github_api_url"
ENV GITHUB_BASE_REF="$github_base_ref"
ENV GITHUB_ENV="$github_env"
ENV GITHUB_EVENT_NAME="$github_event_name"
ENV GITHUB_EVENT_PATH="$github_event_path"
ENV GITHUB_GRAPHQL_URL="$github_graphql_url"
ENV GITHUB_HEAD_REF="$github_head_ref"
ENV GITHUB_JOB="$github_job"
ENV GITHUB_PATH="$github_path"
ENV GITHUB_REF="$github_ref"
ENV GITHUB_REF_NAME="$github_ref_name"
ENV GITHUB_REF_PROTECTED="$github_ref_protected"
ENV GITHUB_REF_TYPE="$github_ref_type"
ENV GITHUB_REPOSITORY="$github_repository"
ENV GITHUB_REPOSITORY_ID="$github_repository_id"
ENV GITHUB_REPOSITORY_OWNER="$github_repository_owner"
ENV GITHUB_REPOSITORY_OWNER_ID="$github_repository_owner_id"
ENV GITHUB_RETENTION_DAYS="$github_retention_days"
ENV GITHUB_RUN_ATTEMPT="$github_run_attempt"
ENV GITHUB_RUN_ID="$github_run_id"
ENV GITHUB_RUN_NUMBER="$github_run_number"
ENV GITHUB_SERVER_URL="$github_server_url"
ENV GITHUB_SHA="$github_sha"
ENV GITHUB_STEP_SUMMARY="$github_step_summary"
ENV GITHUB_WORKFLOW="$github_workflow"
ENV GITHUB_WORKFLOW_REF="$github_workflow_ref"
ENV GITHUB_WORKFLOW_SHA="$github_workflow_sha"
ENV GITHUB_WORKSPACE="$github_workspace"
ENV RUNNER_ARCH="$runner_arch"
ENV RUNNER_DEBUG="$runner_debug"
ENV RUNNER_NAME="$runner_name"
ENV RUNNER_OS="$runner_os"

RUN set -e\
 && apk update --no-cache\
 && apk upgrade --no-cache\
 && apk add --no-cache bash uuidgen curl wget busybox-extras python3 py3-yaml\
 && mkdir -p /conf /hook /over /pack /var/pack

WORKDIR /var/pack

ENTRYPOINT ["bash"]
